name: Build and Upload APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app:
          - name: mongodb
            dockerfile: mongodb/Dockerfile
            context: mongodb
            env: dev
            apkPath: mongodb
            arch: x86_64

    steps:
      - name: Build package using Melange
        uses: chainguard-dev/actions/melange-build-pkg@main
        with:
          config: ${{ matrix.app.name }}.yaml
          archs: ${{ matrix.app.arch }}
          sign-with-key: true
          update-index: true
          repository-append: ${{ github.workspace }}/packages
          keyring-append: /etc/apk/keys/${{ matrix.app.name }}.pub
          workspace-dir: ${{ github.workspace }}/build/${{ matrix.app.name }}
          empty-workspace: ${{ inputs.empty-workspace }}
          signing-key-path: ${{ github.workspace }}/${{ matrix.app.name }}
          source-dir: ${{ matrix.app.context }}

