name: Build and Upload APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app:
          - name: mongodb
            dockerfile: mongodb/Dockerfile
            context: mongodb
            env: dev
            apkPath: mongodbs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download and Install Melange
        run: |
          curl -L "https://github.com/chainguard-dev/melange/releases/download/v0.6.11/melange_0.6.11_linux_386.tar.gz" -o melange.tar.gz
          tar -xzf melange.tar.gz 
          chmod +x melange_0.6.11_linux_386/melange
          cp melange_0.6.11_linux_386/melange /usr/local/bin/melange

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Build package using Melange
        run: |
          melange build --config ${{matrix.app.name}}/.melange.yaml --workspace-dir ${{ github.workspace }}/${{ matrix.app.name }} --source-dir ${{ github.workspace }}/${{ matrix.app.name }} --workdir build --cache-dir cache

      - name: Upload APK as an Artifact (aarch64)
        uses: actions/upload-artifact@v3
        with:
          name: wd-${{ matrix.app.name }}-aarch64-731r0
          path: ${{ matrix.app.apkPath }}/aarch64/war-dog-${{ matrix.app.name }}-7.3.1-r0.apk

      - name: Upload APK as an Artifact (x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: wd-${{ matrix.app.name }}-x86_731r0
          path: ${{ matrix.app.apkPath }}/x86_64/war-dog-${{ matrix.app.name }}-7.3.1-r0.apk