name: Build and Upload APK

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app:
          - name: mongodb
            dockerfile: mongodb/Dockerfile
            context: mongodb
            env: dev
            apkPath: mongodbs
    steps:
      - name: Install Melange
        run: |
          # This is a hypothetical installation command; adjust based on actual installation steps
          sudo apt-get update
          sudo apt-get install melange -y

      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Build package using Melange
        uses: chainguard-dev/actions/melange-build-pkg@main
        with:
          config: '.melange.yaml'  # Path to your Melange config file
          workspace-dir: ${{ github.workspace }}/${{ matrix.app.name }}  # Adjust if your source is in a specific subdirectory
          source-dir: ${{ github.workspace }}/${{ matrix.app.name }}  # Adjust if your source is in a specific subdirectory
          workdir: 'build'  # Temporary working directory for build process
          cache-dir: 'cache'  # Optional: specify a cache directory to speed up builds

      - name: Upload APK as an Artifact (aarch64)
        uses: actions/upload-artifact@v3
        with:
          name: wd-${{ matrix.app.name }}-aarch64-731r0
          path: ${{ matrix.app.apkPath }}/aarch64/war-dog-${{ matrix.app.name }}-7.3.1-r0.apk

      - name: Upload APK as an Artifact (x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: wd-${{ matrix.app.name }}-x86_731r0
          path: ${{ matrix.app.apkPath }}/x86_64/war-dog-${{ matrix.app.name }}-7.3.1-r0.apk
