name: Build and Upload APK

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app:
          - name: mongodb
            dockerfile: mongodb/Dockerfile
            context: mongodb
            env: dev
            apkPath: mongodbs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Build package using Melange with Docker
        run: |
          docker pull cgr.dev/chainguard/melange
          docker run --rm -v ${{ github.workspace }}:/workspace cgr.dev/chainguard/melange build \
            --config /workspace/${{ matrix.app.name }}/.melange.yaml \
            --workspace-dir /workspace/${{ matrix.app.name }} \
            --source-dir /workspace/${{ matrix.app.name }} \
            --workdir /workspace/${{ matrix.app.name }}/build \
            --cache-dir /workspace/${{ matrix.app.name }}/cache

      - name: Upload APK as an Artifact (aarch64)
        uses: actions/upload-artifact@v3
        with:
          name: wd-${{ matrix.app.name }}-aarch64-731r0
          path: ${{ matrix.app.apkPath }}/aarch64/war-dog-${{ matrix.app.name }}-7.3.1-r0.apk

      - name: Upload APK as an Artifact (x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: wd-${{ matrix.app.name }}-x86_731r0
          path: ${{ matrix.app.apkPath }}/x86_64/war-dog-${{ matrix.app.name }}-7.3.1-r0.apk
